import "@/styles/globals.css";

import Navbar from "@/components/navbar/navbar";

export const metadata = {
  title: "Lawyantra",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <div className="main"></div>

      <Navbar />
      <main>
        <div className="gradient" />
        {children}
      </main>
    </body>
  </html>
);

export default RootLayout;
