import "@/styles/globals.css";

import Navbar from "@/components/navbar/navbar";

export const metadata = {
  title: "Lawyantra",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <div className="flex flex-row relative">
        <Navbar />
        <main className="flex flex-col flex-grow relative p-5 pt-8">{children}</main>
      </div>
    </body>
  </html>
);

export default RootLayout;
